github.com:
    users:
        groombook-engineer[bot]:
            oauth_token: ghs_C7uUxDqJJJt7Yo9RGI2NGbXpVf6Cz0393gzt
        scrubs-mcbarkley-ceo[bot]:
            oauth_token: ghs_OPg217JchfWSQ7vGHdA3luTESkSzFb1XqsKm
    user: scrubs-mcbarkley-ceo[bot]
    oauth_token: ghs_OPg217JchfWSQ7vGHdA3luTESkSzFb1XqsKm
